In [32]:
import pandas as pd 
import numpy as np 

imp = pd.read_excel('kpi_data_clean.xlsx')

In [33]:
var = pd.read_csv('kpi_variables.csv')

In [34]:
br = pd.read_csv('branches.csv')

In [35]:
imp

        KDO_BSI var_code    Periode  target_value  realization_value
0     ID0010023       CM 2025-12-01  80298.939592       49505.912433
1     ID0010178       CM 2025-12-01  23342.316089       18712.139757
2     ID0010041       CM 2025-12-01  32003.405492       35749.468069
3     ID0010036       CM 2025-12-01  51241.399969       45714.990754
4     ID0010179       CM 2025-12-01  14583.938521       14885.621720
...         ...      ...        ...           ...                ...
1083  ID0019126      PNS 2025-12-01      0.465385           0.333333
1084  ID0010447      PNS 2025-12-01      0.550000           0.222222
1085  ID0018206      PNS 2025-12-01      0.683333           0.333333
1086  ID0010525      PNS 2025-12-01      0.516667           0.200000
1087  ID0010156      PNS 2025-12-01      0.707143           0.222222

[1088 rows x 5 columns]

In [36]:
imp = imp.merge(
    br[['branch_id', 'KDO_BSI']],
    left_on='KDO_BSI',
    right_on='KDO_BSI',
    how='left'
)
imp = imp.merge(
    var[['variable_id', 'var_code']],
    left_on='var_code',
    right_on='var_code',
    how='left'
)
imp

,KDO_BSI,var_code,Periode,target_value,realization_value,branch_id,variable_id
0,ID0010023,CM,2025-12-01,80298.939592,49505.912433,27,1
1,ID0010178,CM,2025-12-01,23342.316089,18712.139757,30,1
2,ID0010041,CM,2025-12-01,32003.405492,35749.468069,29,1
3,ID0010036,CM,2025-12-01,51241.399969,45714.990754,28,1
4,ID0010179,CM,2025-12-01,14583.938521,14885.621720,31,1
...,...,...,...,...,...,...,...
1083,ID0019126,PNS,2025-12-01,0.465385,0.333333,64,16
1084,ID0010447,PNS,2025-12-01,0.550000,0.222222,59,16
1085,ID0018206,PNS,2025-12-01,0.683333,0.333333,68,16
1086,ID0010525,PNS,2025-12-01,0.516667,0.200000,61,16
1087,ID0010156,PNS,2025-12-01,0.707143,0.222222,54,16

In [37]:
target = imp[['branch_id', 'variable_id', 'Periode','target_value']]
target

      branch_id  variable_id    Periode  target_value
0            27            1 2025-12-01  80298.939592
1            30            1 2025-12-01  23342.316089
2            29            1 2025-12-01  32003.405492
3            28            1 2025-12-01  51241.399969
4            31            1 2025-12-01  14583.938521
...         ...          ...        ...           ...
1083         64           16 2025-12-01      0.465385
1084         59           16 2025-12-01      0.550000
1085         68           16 2025-12-01      0.683333
1086         61           16 2025-12-01      0.516667
1087         54           16 2025-12-01      0.707143

[1088 rows x 4 columns]

In [38]:
realization = imp[['branch_id', 'variable_id', 'Periode','realization_value']]
realization

      branch_id  variable_id    Periode  realization_value
0            27            1 2025-12-01       49505.912433
1            30            1 2025-12-01       18712.139757
2            29            1 2025-12-01       35749.468069
3            28            1 2025-12-01       45714.990754
4            31            1 2025-12-01       14885.621720
...         ...          ...        ...                ...
1083         64           16 2025-12-01           0.333333
1084         59           16 2025-12-01           0.222222
1085         68           16 2025-12-01           0.333333
1086         61           16 2025-12-01           0.200000
1087         54           16 2025-12-01           0.222222

[1088 rows x 4 columns]

In [39]:
var_calc = target.merge(realization, on=['branch_id', 'variable_id', 'Periode'])
var_calc

      branch_id  variable_id    Periode  target_value  realization_value
0            27            1 2025-12-01  80298.939592       49505.912433
1            30            1 2025-12-01  23342.316089       18712.139757
2            29            1 2025-12-01  32003.405492       35749.468069
3            28            1 2025-12-01  51241.399969       45714.990754
4            31            1 2025-12-01  14583.938521       14885.621720
...         ...          ...        ...           ...                ...
1083         64           16 2025-12-01      0.465385           0.333333
1084         59           16 2025-12-01      0.550000           0.222222
1085         68           16 2025-12-01      0.683333           0.333333
1086         61           16 2025-12-01      0.516667           0.200000
1087         54           16 2025-12-01      0.707143           0.222222

[1088 rows x 5 columns]

In [40]:
var_calc = var_calc.merge(
    var[['variable_id','var_code','weight','type','category_id']],
    left_on='variable_id',
    right_on='variable_id'
)

In [41]:
var_calc['pencapaian'] = var_calc['realization_value'] / var_calc['target_value']

In [ ]:
# def calculate_pencapaian(row):
#     if row['type'] == 'POSITIF':
#         return row['realization_value'] / row['target_value'] if row['target_value'] != 0 else 0
#     else:  
#         return row['target_value'] / row['realization_value'] if row['realization_value'] != 0 else 0

# var_calc['pencapaian'] = var_calc.apply(calculate_pencapaian, axis=1)

# var_calc

,branch_id,variable_id,Periode,target_value,realization_value,var_code,weight,type,category_id,pencapaian
0,27,1,2025-12-01,80298.939592,49505.912433,CM,0.10,POSITIF,1,0.616520
1,30,1,2025-12-01,23342.316089,18712.139757,CM,0.10,POSITIF,1,0.801640
2,29,1,2025-12-01,32003.405492,35749.468069,CM,0.10,POSITIF,1,1.117052
3,28,1,2025-12-01,51241.399969,45714.990754,CM,0.10,POSITIF,1,0.892150
4,31,1,2025-12-01,14583.938521,14885.621720,CM,0.10,POSITIF,1,1.020686
...,...,...,...,...,...,...,...,...,...,...
1083,64,16,2025-12-01,0.465385,0.333333,PNS,0.75,NEGATIF,4,1.396154
1084,59,16,2025-12-01,0.550000,0.222222,PNS,0.75,NEGATIF,4,2.475000
1085,68,16,2025-12-01,0.683333,0.333333,PNS,0.75,NEGATIF,4,2.050000
1086,61,16,2025-12-01,0.516667,0.200000,PNS,0.75,NEGATIF,4,2.583333
1087,54,16,2025-12-01,0.707143,0.222222,PNS,0.75,NEGATIF,4,3.182143

In [43]:
var_calc['max_target'] = var_calc['pencapaian'].clip(upper=1.5)

In [44]:
var_calc['score'] = var_calc['weight'] * var_calc['max_target'] * 100

In [45]:
var_calc

,branch_id,variable_id,Periode,target_value,realization_value,var_code,weight,type,category_id,pencapaian,max_target,score
0,27,1,2025-12-01,80298.939592,49505.912433,CM,0.10,POSITIF,1,0.616520,0.616520,6.165201
1,30,1,2025-12-01,23342.316089,18712.139757,CM,0.10,POSITIF,1,0.801640,0.801640,8.016402
2,29,1,2025-12-01,32003.405492,35749.468069,CM,0.10,POSITIF,1,1.117052,1.117052,11.170520
3,28,1,2025-12-01,51241.399969,45714.990754,CM,0.10,POSITIF,1,0.892150,0.892150,8.921495
4,31,1,2025-12-01,14583.938521,14885.621720,CM,0.10,POSITIF,1,1.020686,1.020686,10.206860
...,...,...,...,...,...,...,...,...,...,...,...,...
1083,64,16,2025-12-01,0.465385,0.333333,PNS,0.75,NEGATIF,4,1.396154,1.396154,104.711538
1084,59,16,2025-12-01,0.550000,0.222222,PNS,0.75,NEGATIF,4,2.475000,1.500000,112.500000
1085,68,16,2025-12-01,0.683333,0.333333,PNS,0.75,NEGATIF,4,2.050000,1.500000,112.500000
1086,61,16,2025-12-01,0.516667,0.200000,PNS,0.75,NEGATIF,4,2.583333,1.500000,112.500000
1087,54,16,2025-12-01,0.707143,0.222222,PNS,0.75,NEGATIF,4,3.182143,1.500000,112.500000

In [47]:
tes = var_calc[[
    'branch_id',
    'var_code',
    'target_value',
    'realization_value',
    'pencapaian',
    'max_target',
    'weight',
    'score'
]]
tes['pencapaian_%'] = tes['pencapaian'] * 100
tes['max_target_%'] = tes['max_target'] * 100

tes[tes['var_code'] == "NPF"]

C:\Users\diana\AppData\Local\Temp\ipykernel_27136\2520929431.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tes['pencapaian_%'] = tes['pencapaian'] * 100
C:\Users\diana\AppData\Local\Temp\ipykernel_27136\2520929431.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tes['max_target_%'] = tes['max_target'] * 100

,branch_id,var_code,target_value,realization_value,pencapaian,max_target,weight,score,pencapaian_%,max_target_%
680,27,NPF,5648.938257,4347.133766,1.299463,1.299463,0.25,32.486568,129.946272,129.946272
681,30,NPF,68.804037,22.576055,3.047655,1.500000,0.25,37.500000,304.765546,150.000000
682,29,NPF,773.859849,2383.356276,0.324693,0.324693,0.25,8.117333,32.469331,32.469331
683,28,NPF,7845.990611,11821.856186,0.663685,0.663685,0.25,16.592129,66.368517,66.368517
684,31,NPF,1322.449152,2180.262455,0.606555,0.606555,0.25,15.163876,60.655503,60.655503
...,...,...,...,...,...,...,...,...,...,...
743,64,NPF,8435.185156,11454.320395,0.736420,0.736420,0.25,18.410488,73.641952,73.641952
744,59,NPF,5722.046401,7987.571585,0.716369,0.716369,0.25,17.909218,71.636872,71.636872
745,68,NPF,39.343700,684.239948,0.057500,0.057500,0.25,1.437496,5.749986,5.749986
746,61,NPF,205.589597,3925.194581,0.052377,0.052377,0.25,1.309423,5.237692,5.237692
747,54,NPF,1296.398321,1490.233438,0.869930,0.869930,0.25,21.748242,86.992970,86.992970